# Generated by Django 2.0.6 on 2021-09-08 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cita',
            fields=[
                ('pk_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_y_hora', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('pk_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('name_cliente', models.CharField(default='n/a', max_length=80)),
                ('Dpi', models.BigIntegerField()),
                ('Edad', models.BigIntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('imagen', models.URLField(default='https://i.postimg.cc/QxHRwhTK/png-transparent-user-profile-computer-icons-user-interface-mystique-miscellaneous-user-interface-des.png')),
            ],
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('pk_medico', models.AutoField(primary_key=True, serialize=False)),
                ('name_medico', models.CharField(default='n/a', max_length=80)),
                ('especialidad', models.CharField(max_length=100)),
                ('turno', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('pk_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('chequeo_medico', models.CharField(max_length=200)),
                ('precio', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='fk_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webjosue.cliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fk_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webjosue.servicio'),
        ),
    ]
